ARG OPENGAUSS_DEV_BASE_IMAGE=docker.1ms.run/openeuler/openeuler:24.03-lts
ARG OPENGAUSS_BUILD_TYPE=debug
ARG OPENGAUSS_INSTALL_PREFIX=/opt/opengauss/install

FROM ${OPENGAUSS_DEV_BASE_IMAGE}
ARG OPENGAUSS_BUILD_TYPE
ARG OPENGAUSS_INSTALL_PREFIX
ENV LANG=C.utf8
ENV LC_ALL=C.utf8
ENV OPENGAUSS_BUILD_TYPE=${OPENGAUSS_BUILD_TYPE}
ENV OPENGAUSS_INSTALL_PREFIX=${OPENGAUSS_INSTALL_PREFIX}

RUN yum -y update \
    && yum -y install \
      bash \
      bison \
      binutils \
      bzip2 \
      ca-certificates \
      dkms \
      expect \
      flex \
      gcc \
      gcc-c++ \
      gdb \
      gdb-gdbserver \
      git \
      glibc-all-langpacks \
      glibc-common \
      glibc-devel \
      java-1.8.0-openjdk-devel \
      krb5-devel \
      libaio-devel \
      libedit-devel \
      libevent-devel \
      libffi-devel \
      libxml2-devel \
      lz4-devel \
      make \
      ncurses-devel \
      net-tools \
      numactl-devel \
      openblas-devel \
      openssl-devel \
      patch \
      perl \
      procps-ng \
      python3 \
      readline-devel \
      rsync \
      sudo \
      tar \
      unixODBC-devel \
      wget \
      which \
      zlib-devel \
    && yum clean all \
    && rm -rf /var/cache/yum \
    && localedef -i en_US -f UTF-8 en_US.UTF-8 || true

RUN groupadd -g 1000 omm \
    && useradd -m -u 1000 -g 1000 -s /bin/bash omm \
    && mkdir -p /workspace /workspace/opengauss-build /var/log/opengauss /opt/opengauss/install \
    && chown -R omm:omm /workspace /var/log/opengauss /opt/opengauss

COPY env/opengauss/dev/scripts/dev-build.sh /usr/local/bin/dev-build.sh
COPY env/opengauss/dev/scripts/dev-configure.sh /usr/local/bin/dev-configure.sh
COPY env/opengauss/dev/scripts/dev-run.sh /usr/local/bin/dev-run.sh
COPY env/opengauss/dev/scripts/dev-debug.sh /usr/local/bin/dev-debug.sh
RUN chmod +x /usr/local/bin/dev-build.sh /usr/local/bin/dev-configure.sh /usr/local/bin/dev-run.sh /usr/local/bin/dev-debug.sh

USER omm
WORKDIR /workspace/openGauss-server
CMD ["bash"]
